Repository Team7-OpenMind/OpenMind, pull requests merged in 2024-01, with the labels that each got.

#11 OM-24 프로젝트 기본 파일 수정
  .gitignore
  public/index.html
  src/App.jsx
  src/common.css
  src/index.js
  src/stories/Header.jsx
Labels: Setting

#13 OM-26/OM-15 로딩 컴포넌트 추가 및 QuestionList 컴포넌트 추가
  src/api/index.js
  src/api/questionApi.js
  src/assets/loading.gif
  src/components/index.jsx
  src/components/loading/Loading.jsx
  src/components/question/QuestionList.jsx
  src/hooks/useQuery.js
  src/pages/Post.jsx
Labels: Refactor, Feature

#16 OM-15 QuestionList 컴포넌트 내에 질문 작성하기 버튼 추가
  src/common.css
  src/components/question/QuestionList.jsx
  src/hooks/useMediaQuery.js
  src/pages/Post.jsx
Labels: Feature

#15 OM-27 오류 화면 추가
  src/components/error/Error.jsx
  src/components/loading/Loading.jsx
  src/components/question/QuestionList.jsx
  src/hooks/useQuery.js
  src/pages/Post.jsx
Labels: Feature

#17 OM-34 질문 목록 페이지에서 질문피드 페이지로 이동
  src/App.jsx
  src/components/Card.jsx
  src/components/CardList.jsx
  src/pages/Post.jsx
Labels: Feature

#18 OM-14 질문 피드 화면 구현
  src/components/feedCard/FeedCard.jsx
  src/components/question/QuestionList.jsx
  src/pages/Post.jsx
  src/utils/date.js
Labels: Feature

#23 OM-37 bug: 모바일 사이즈(375px) 적용
  src/pages/List.jsx
Labels: Bug

#22 OM-18 메인 페이지 레이아웃 구현
  src/components/header/main/Header.jsx
  src/components/header/main/HeaderMobile.jsx
  src/components/header/main/logo/Logo.jsx
  src/components/header/main/logo/LogoMobile.jsx
  src/components/inputBar/SignInputBar.jsx
  src/pages/Home.jsx
Labels: Feature

#20 OM-11 feat: 공유하기(카카오, 페이스북) 및 클립보드 기능 구현
  .env
  package-lock.json
  public/index.html
  src/App.jsx
  src/api/questionApi.js
  src/assets/Arrow-right.svg
  src/assets/Arrow.svg
  src/common.css
  src/components/Card.jsx
  src/components/CardList.jsx
  src/components/error/Error.jsx
  src/components/feedCard/FeedCard.jsx
  src/components/loading/Loading.jsx
  src/components/question/QuestionList.jsx
  src/components/userCard/Dropdown.jsx
  src/hooks/useMediaQuery.js
  src/hooks/useQuery.js
  src/pages/List.jsx
  src/pages/Post.jsx
  src/utils/ResizeObserver.jsx
  src/utils/date.js
  src/utils/share.js
Labels: Feature

#25 OM-11 feat: 카카오톡, 페이스북 공유하기 기능 구현
  .env
  package-lock.json
  public/index.html
  src/components/userCard/Dropdown.jsx
  src/pages/List.jsx
  src/utils/ResizeObserver.jsx
  src/utils/share.js
Labels: Feature

#19 OM-36 QA페이지 header 컴포넌트
  src/assets/Facebook.svg
  src/assets/Kakaotalk.svg
  src/assets/Link.svg
  src/assets/header.png
  src/components/QA-Header.jsx
Labels: Feature

#24 OM-14 질문 피드 반응형 오류 수정 및 미답변/답변 거절/답변 완료 상태 추가
  src/components/feedCard/FeedCard.jsx
  src/components/index.jsx
  src/components/question/QuestionList.jsx
Labels: Bug, Feature

#28 OM-41 메인 페이지 기능 구현
  src/api/questionApi.js
  src/components/header/main/Header.jsx
  src/components/header/main/HeaderMobile.jsx
  src/components/inputBar/SignInputBar.jsx
  src/pages/Home.jsx
Labels: Feature

#29 OM-24 Query Client 기본 옵션 설정 및 axios.interceptors 설정으로 useQuery 리팩토링
  src/components/question/QuestionList.jsx
  src/hooks/useQuery.js
  src/index.js
Labels: Refactor

#33 OM-40 리액션 기능 구현
  src/api/reactionApi.js
  src/assets/thumbs-down.svg
  src/assets/thumbs-up.svg
  src/components/reaction/Reaction.jsx
  src/components/reaction/reaction.css
Labels: Feature

#30 OM-43 feat: toast component 추가 및 env파일 git에서 제거
  .env
  .gitignore
  src/components/CardList.jsx
  src/components/question/QuestionList.jsx
  src/components/toast/toast.jsx
  src/pages/List.jsx
  src/utils/share.js
Labels: Feature

#31 OM-13 chore: webpack 설정
  package-lock.json
  package.json
  src/api/questionApi.js
  src/index.js
  webpack.config.js
Labels: Deploy

#26 OM-38 Test: FeedCard.test.js 추가 및 디렉토리 정리
  src/components/Card.jsx
  src/components/button/Dropdown.jsx
  src/components/feedCard/FeedCard.test.js
  src/components/userCard/UserCard.jsx
  src/components/userCard/UserCard.test.js
  src/components/userCard/UserCardCmp.jsx
  src/components/userCard/UserCardList.jsx
  src/pages/List.jsx
Labels: Test

#34 OM-35 질문 리스트 페이지 페이지네이션 구현
  src/components/pagination/Pagination.jsx
  src/components/pagination/button/NextButton.jsx
  src/components/pagination/button/PrevButton.jsx
  src/components/userCard/UserCardList.jsx
  src/pages/List.jsx
  src/utils/pagination.js
  src/utils/pagination.test.js
Labels: Feature

#35 OM-24 Redux-toolkit 추가 및 PR에 대한 Lint 검사와 Jest 테스트 추가
  .babelrc
  .github/workflow/check-pr.yml
  babel.config.js
  jest.config.js
  package-lock.json
  package.json
  src/index.js
  src/pages/Post.jsx
  src/store/index.js
  src/store/subjectSlice.js
  src/store/types.d.ts
  src/store/userSlice.js
Labels: Feature, Setting

#37 OM-48 deploy fix: webpack output 경로 변경(dist->build)
  webpack.config.js
Labels: Bug, Deploy

#39 OM-50 질문 작성 날짜에 피드 생성 날짜가 잘못 들어가는 문제 해결
  src/components/feedCard/FeedCard.jsx
  src/components/question/QuestionList.jsx
  src/pages/Post.jsx
Labels: Bug, Refactor

#38 OM-44 feat: link및 filter 기능 구현
  src/api/questionApi.js
  src/components/userCard/UserCardList.jsx
  src/pages/List.jsx
Labels: Feature

#40 OM-52 fix: emptySVG에 잘못된 style이 적용되는 현상 수정
  src/components/question/QuestionList.jsx
  src/components/toast/Toast.jsx
Labels: Bug

#41 OM-40 삭제하기 기능 구현, 각 컴포넌트기능 합치기, reaction 기능 수정
  src/api/answerApi.js
  src/api/reactionApi.js
  src/components/AnswerCard.jsx
  src/components/Delete-QA.jsx
  src/components/QA-Header.jsx
  src/components/answer/AnswerComponent.jsx
  src/components/answer/AnswerPageCard.jsx
  src/components/answer/AnswerPageList.jsx
  src/components/answerUpdate/AnswerUpdate.jsx
  src/components/feedCard/FeedCard.jsx
  src/components/question/QuestionList.jsx
  src/components/reaction/Reaction.jsx
  src/pages/Answer.jsx
  src/pages/Post.jsx
Labels: Bug, Refactor, Feature

#42 OM-51 질문 캐시를 위한 Redux-toolkit questionSlice 추가
  src/components/index.jsx
  src/components/question/QuestionList.jsx
  src/hooks/types.d.ts
  src/pages/Post.jsx
  src/store/index.js
  src/store/questionSlice.js
  src/store/subjectSlice.js
  src/store/types.d.ts
  src/store/userSlice.js
  src/types.d.ts
Labels: Feature

#43 feat: OM-42 질문 작성 모달 구현
  public/index.html
  src/assets/Close.svg
  src/assets/Messages.svg
  src/components/modal/Modal.jsx
  src/components/modal/question/QuestionModal.jsx
  src/pages/Post.jsx
Labels: Feature

#45 OM-54 질문 리스트 중복 방지 및 질문 작성 시 QuestionList 상태 초기화
  src/components/modal/question/QuestionModal.jsx
  src/components/question/QuestionList.jsx
  src/pages/Post.jsx
  src/store/questionSlice.js
Labels: Bug

#47 OM-20 수정하기 버튼 아이콘으로 변경
  src/api/answerApi.js
  src/assets/pencil-square.svg
  src/components/answer/AnswerPageCard.jsx
  src/components/answer/AnswerPageList.jsx
  src/pages/Answer.jsx
Labels: Refactor, HTML&CSS

#49 OM-22 refactor: 삭제하기 기능 새로고침 없이 동작하게 수정
  src/api/answerApi.js
  src/components/answer/AnswerPageList.jsx
  src/pages/Answer.jsx
Labels: Refactor, Feature

#46 OM-53 feat: 공유하기 기능 연결 BASE_URL에서만 동작
  src/components/QA-Header.jsx
  src/components/toast/Toast.jsx
Labels: Feature

#50 OM-55 fix: 무한스크롤 로고 겹치는 문제 수정
  src/components/question/QuestionList.jsx
Labels: Bug

#48 OM-36 QA-header 컴포넌트에 로고 클릭시 list페이지로 이동하게 하는 기능 추가 + list페이지로 돌아가는 버튼 추가
  src/components/QA-Header.jsx
  src/components/answer/AnswerPageList.jsx
  src/pages/Post.jsx
Labels: Refactor, Feature

#52 docs: Update README.md
  README.md
Labels: Docs

#51 OM-57 refactor: Reaction 데이터 표시 방식 수정
  src/components/reaction/Reaction.jsx
Labels: Refactor

#53 OM-61 질문 작성 모달에서 내용 없으면 버튼 비활성화
  src/components/modal/Modal.jsx
  src/components/modal/question/QuestionModal.jsx
Labels: Bug

#54 OM-59 Post 컴포넌트에 답변 작성하기 버튼 추가
  src/pages/Post.jsx
Labels: Feature

#57 OM-59 질문이 없을 때 답변 작성하기 버튼 숨기도록 위치 변경
  src/pages/Post.jsx
Labels: HTML&CSS

#58 OM-62 fix: 공유하기 기능 버그 수정
  src/api/index.js
  src/components/QA-Header.jsx
Labels: Bug
